<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hardening.Core\Hardening.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="10.0.12" />
  </ItemGroup>

</Project>
